package JSON.behavior;

/*Generated by MPS */


public class JSONBoolean_BehaviorDescriptor extends JSONValue_BehaviorDescriptor {
  public JSONBoolean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSON.structure.JSONBoolean";
  }
}
