package JSON.behavior;

/*Generated by MPS */


public abstract class JSONValue_BehaviorDescriptor extends JSONElement_BehaviorDescriptor {
  public JSONValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSON.structure.JSONValue";
  }
}
