package JSON.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class JSONElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public JSONElement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSON.structure.JSONElement";
  }
}
