package JSON.behavior;

/*Generated by MPS */


public class JSONInteger_BehaviorDescriptor extends JSONValue_BehaviorDescriptor {
  public JSONInteger_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSON.structure.JSONInteger";
  }
}
